--Functions--

SELECT COUNT(*) FROM SALARY; 

SELECT SUM(EmpSalary) FROM SALARY;  

SELECT AVG(EmpSalary) FROM SALARY;  

SELECT MAX(EmpSalary) FROM SALARY;  

SELECT MIN(EmpSalary) FROM SALARY;

SELECT ABS(EmpSalary) 

SELECT FLOOR(239.88), FLOOR(-334.45) 

SELECT CEILING(239.28), CEILING(-334.45) 

SELECT SQRT(9), SQRT(100);  

SELECT REVERSE('kabir');
 